#include <stdio.h>
#include <stdlib.h>
unsigned long long int shulie(unsigned long long int n)
{

	while (n != 1)
	{

		if (n % 2)
		{
			n = (3 * n + 1);
		}

		else
		{
			n = (n / 2);
		}
		return n;
	}
	return 0;
}
int main()
{
	unsigned long long int m;

	while ((scanf("%llu", &m)) != EOF)

	{
		int i = 1;
		printf("Hailstone generated by %llu:\n", m);
		printf("%llu", m);
		while (m != 1)
		{
			printf(" %llu", shulie(m));
			m = shulie(m);
			i++;
		}
		printf("\n");
		printf("Number of hailstone generated:%d", i);
		printf("\n\n");

	}
	
	return 0;
}

	






